In [2]:
import pandas as pd
df = pd.read_csv("Bollywood_Films.csv")

In [3]:
df

,Actor Name,Film,Year,Genre,Box Office (₹ Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Drama,2024,8.4
3,Hrithik Roshan,War,2019,Action,475,6.5
4,Akshay Kumar,Kesari,2019,Historical,207,7.4
5,Ranbir Kapoor,Sanju,2018,Biopic,586,7.8
6,Deepika Padukone,Padmaavat,2018,Historical,585,7.0
7,Ranveer Singh,Bajirao Mastani,2015,Historical,356,7.2
8,Alia Bhatt,Raazi,2018,Thriller,196,7.7
9,Ajay Devgn,Tanhaji,2020,Historical,368,7.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror-Comedy,266,6.6
11,Vicky Kaushal,URI: The Surgical Strike,2019,Action,342,8.2
12,Shahid Kapoor,Kabir Singh,2019,Drama,379,7.1
13,Varun Dhawan,Bhediya,2022,Comedy-Horror,89,7.3
14,John Abraham,Parmanu,2018,Drama,65,7.7

In [4]:
df['Actor Name']

0       Shah Rukh Khan
1          Salman Khan
2           Aamir Khan
3       Hrithik Roshan
4         Akshay Kumar
5        Ranbir Kapoor
6     Deepika Padukone
7        Ranveer Singh
8           Alia Bhatt
9           Ajay Devgn
10       Kartik Aaryan
11       Vicky Kaushal
12       Shahid Kapoor
13        Varun Dhawan
14        John Abraham
Name: Actor Name, dtype: object

In [5]:
df[['Actor Name', 'IMDb']]

          Actor Name  IMDb
0     Shah Rukh Khan   7.0
1        Salman Khan   6.0
2         Aamir Khan   8.4
3     Hrithik Roshan   6.5
4       Akshay Kumar   7.4
5      Ranbir Kapoor   7.8
6   Deepika Padukone   7.0
7      Ranveer Singh   7.2
8         Alia Bhatt   7.7
9         Ajay Devgn   7.6
10     Kartik Aaryan   6.6
11     Vicky Kaushal   8.2
12     Shahid Kapoor   7.1
13      Varun Dhawan   7.3
14      John Abraham   7.7

In [6]:
df

,Actor Name,Film,Year,Genre,Box Office (₹ Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Drama,2024,8.4
3,Hrithik Roshan,War,2019,Action,475,6.5
4,Akshay Kumar,Kesari,2019,Historical,207,7.4
5,Ranbir Kapoor,Sanju,2018,Biopic,586,7.8
6,Deepika Padukone,Padmaavat,2018,Historical,585,7.0
7,Ranveer Singh,Bajirao Mastani,2015,Historical,356,7.2
8,Alia Bhatt,Raazi,2018,Thriller,196,7.7
9,Ajay Devgn,Tanhaji,2020,Historical,368,7.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror-Comedy,266,6.6
11,Vicky Kaushal,URI: The Surgical Strike,2019,Action,342,8.2
12,Shahid Kapoor,Kabir Singh,2019,Drama,379,7.1
13,Varun Dhawan,Bhediya,2022,Comedy-Horror,89,7.3
14,John Abraham,Parmanu,2018,Drama,65,7.7

In [8]:
df.loc[1]

Actor Name                  Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
Box Office (₹ Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [10]:
df[df['IMDb'] > 8]

,Actor Name,Film,Year,Genre,Box Office (₹ Crore),IMDb
2,Aamir Khan,Dangal,2016,Drama,2024,8.4
11,Vicky Kaushal,URI: The Surgical Strike,2019,Action,342,8.2